### ISSUE TITLE
パッシブスキルについて

### ISSUE THREAD

**Issue by kuuzya** [napo-sawada/era4X#48]
3800fa9059bfec1b0dd17106ecf27f3953f978b7 にてスキルの整理があり, tohoKでのスキルの殆どが削除されました. 現在PASSIVEスキルである超成長力から工作員までのスキル自体や効果処理の実装が削除されていませんが, SKILL_GENREから受動が消えているため取得だけできないような状況です.
パッシブスキルについてこのあとどのようにされる予定でしょうか.

**Comment by napo-sawada** [comment]
@kuuzya 
パッシブスキルというかスキル全般に関してですが、Kのスキルは削除する予定です。
なぜ現状削除できていないのかというと、私が他のコンテンツにうつつを抜かしているためです...
スキルアップデートのタイミングで修正したいと思います

**Comment by kuuzya** [comment]
了解です こちらでも削除できるタイミングで削除します
